{% set name = "tethys_dataset_services" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a195d0de2e81b7d8e5f206109b0826fba95531f67aab030290d9ed732e490d91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django
    - future
    - jinja2
    - owslib
    - geoserver-restconfig
    - requests
    - requests-toolbelt
    - sqlalchemy
    - psycopg2
    - psycopg2-binary

test:
  imports:
    - tethys_dataset_services
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tethysplatform/tethys_dataset_services
  summary: A generic Python interface for dataset services such as GeoServer, CKAN, and HydroShare
  description: |
    Tethys datasets provides a Python API for various 
    dataset services such as GeoServer, CKAN, and HydroShare.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: http://docs.tethysplatform.org/en/stable/tethys_sdk/tethys_services/spatial_dataset_services.html#spatial-dataset-engine-references
  dev_url: https://github.com/tethysplatform/tethys_dataset_services

extra:
  recipe-maintainers:
    - swainn
